# Generated by Django 6.0.2 on 2026-02-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_rename_description_herb_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herbs', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='herb',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
    ]
