# Generated by Django 6.0.2 on 2026-02-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_herb_category_alter_herb_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herbs', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='MedicalUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_uses', to='catalog.herb')),
            ],
            options={
                'unique_together': {('name', 'herb')},
            },
        ),
    ]
