# Generated by Django 6.0.2 on 2026-02-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_herb_category_medicaluse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaluse',
            name='observation',
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.medicaluse')),
            ],
        ),
    ]
