# Generated by Django 6.0.2 on 2026-02-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_herb_category_medicaluse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaluse',
            old_name='description',
            new_name='observation',
        ),
    ]
