# Generated by Django 6.0.2 on 2026-02-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_medicaluse_observation_observation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicaluse',
            unique_together={('name', 'herb')},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='overview_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='overview_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaluse',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicaluse',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='content_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicaluse',
            unique_together={('name', 'herb'), ('name_en', 'herb'), ('name_pt_br', 'herb')},
        ),
    ]
